#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Eiki Nakayama <qwertyuiop1103566@gmail.com>
# SPDX-License-Identifier: GPL-3.0-only

import sys
import math

#ループ
for line in sys.stdin:

    try:

        n = float(line.strip())

        if n < 1:
            continue

        lognovalue = math.log10(n)

        
        length = int(lognovalue * 20) 

        print(f"{n:7.2f} | {lognovalue:6.6f} | {'0' * length}")

    except ValueError:
        
        continue
